name = "LeanSearchClient"
testDriver = "LeanSearchClientTest"
defaultTargets = ["LeanSearchClient"]
leanOptions = { experimental.module = true }

[[lean_lib]]
name = "LeanSearchClient"

[[lean_lib]]
name = "LeanSearchClientTest"
